/** @format */

const example = [
    {
        time: '2023-08-23 18:00:00',
        mainInfo: {
            temp: 295.4,
            feels_like: 295.93,
            temp_min: 295.15,
            temp_max: 295.4,
            pressure: 1014,
            sea_level: 1014,
            grnd_level: 1011,
            humidity: 86,
            temp_kf: 0.25,
        },
        weatherInfo: {
            id: 802,
            main: 'Clouds',
            description: 'scattered clouds',
            icon: '03n',
        },
        cloudsInfo: {
            all: 46,
        },
        windInfo: {
            speed: 1.99,
            deg: 112,
            gust: 3.09,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0,
        partOfTheDay: 'n',
    },
    {
        time: '2023-08-23 21:00:00',
        mainInfo: {
            temp: 295.38,
            feels_like: 295.93,
            temp_min: 295.3,
            temp_max: 295.38,
            pressure: 1013,
            sea_level: 1013,
            grnd_level: 1010,
            humidity: 87,
            temp_kf: 0.08,
        },
        weatherInfo: {
            id: 803,
            main: 'Clouds',
            description: 'broken clouds',
            icon: '04n',
        },
        cloudsInfo: {
            all: 57,
        },
        windInfo: {
            speed: 2.34,
            deg: 108,
            gust: 3.93,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0,
        partOfTheDay: 'n',
    },
    {
        time: '2023-08-24 00:00:00',
        mainInfo: {
            temp: 296.5,
            feels_like: 297.01,
            temp_min: 296.5,
            temp_max: 296.5,
            pressure: 1014,
            sea_level: 1014,
            grnd_level: 1012,
            humidity: 81,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 803,
            main: 'Clouds',
            description: 'broken clouds',
            icon: '04d',
        },
        cloudsInfo: {
            all: 56,
        },
        windInfo: {
            speed: 1.58,
            deg: 91,
            gust: 3.56,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0,
        partOfTheDay: 'd',
    },
    {
        time: '2023-08-24 03:00:00',
        mainInfo: {
            temp: 301.59,
            feels_like: 303.27,
            temp_min: 301.59,
            temp_max: 301.59,
            pressure: 1013,
            sea_level: 1013,
            grnd_level: 1011,
            humidity: 60,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 800,
            main: 'Clear',
            description: 'clear sky',
            icon: '01d',
        },
        cloudsInfo: {
            all: 10,
        },
        windInfo: {
            speed: 4.18,
            deg: 147,
            gust: 4.94,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0,
        partOfTheDay: 'd',
    },
    {
        time: '2023-08-24 06:00:00',
        mainInfo: {
            temp: 301.86,
            feels_like: 303.7,
            temp_min: 301.86,
            temp_max: 301.86,
            pressure: 1011,
            sea_level: 1011,
            grnd_level: 1009,
            humidity: 60,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 801,
            main: 'Clouds',
            description: 'few clouds',
            icon: '02d',
        },
        cloudsInfo: {
            all: 14,
        },
        windInfo: {
            speed: 6.63,
            deg: 156,
            gust: 7.13,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0,
        partOfTheDay: 'd',
    },
    {
        time: '2023-08-24 09:00:00',
        mainInfo: {
            temp: 300.48,
            feels_like: 302.01,
            temp_min: 300.48,
            temp_max: 300.48,
            pressure: 1010,
            sea_level: 1010,
            grnd_level: 1008,
            humidity: 64,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 800,
            main: 'Clear',
            description: 'clear sky',
            icon: '01d',
        },
        cloudsInfo: {
            all: 4,
        },
        windInfo: {
            speed: 6.02,
            deg: 143,
            gust: 7.82,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0,
        partOfTheDay: 'd',
    },
    {
        time: '2023-08-24 12:00:00',
        mainInfo: {
            temp: 296.67,
            feels_like: 297.24,
            temp_min: 296.67,
            temp_max: 296.67,
            pressure: 1012,
            sea_level: 1012,
            grnd_level: 1010,
            humidity: 83,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 800,
            main: 'Clear',
            description: 'clear sky',
            icon: '01n',
        },
        cloudsInfo: {
            all: 3,
        },
        windInfo: {
            speed: 3.49,
            deg: 121,
            gust: 6.29,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0,
        partOfTheDay: 'n',
    },
    {
        time: '2023-08-24 15:00:00',
        mainInfo: {
            temp: 295.75,
            feels_like: 296.39,
            temp_min: 295.75,
            temp_max: 295.75,
            pressure: 1014,
            sea_level: 1014,
            grnd_level: 1011,
            humidity: 89,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 800,
            main: 'Clear',
            description: 'clear sky',
            icon: '01n',
        },
        cloudsInfo: {
            all: 3,
        },
        windInfo: {
            speed: 2.08,
            deg: 112,
            gust: 3.73,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0,
        partOfTheDay: 'n',
    },
    {
        time: '2023-08-24 18:00:00',
        mainInfo: {
            temp: 295.36,
            feels_like: 296.04,
            temp_min: 295.36,
            temp_max: 295.36,
            pressure: 1012,
            sea_level: 1012,
            grnd_level: 1010,
            humidity: 92,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 801,
            main: 'Clouds',
            description: 'few clouds',
            icon: '02n',
        },
        cloudsInfo: {
            all: 16,
        },
        windInfo: {
            speed: 1.54,
            deg: 110,
            gust: 4.32,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0,
        partOfTheDay: 'n',
    },
    {
        time: '2023-08-24 21:00:00',
        mainInfo: {
            temp: 294.55,
            feels_like: 295.15,
            temp_min: 294.55,
            temp_max: 294.55,
            pressure: 1011,
            sea_level: 1011,
            grnd_level: 1009,
            humidity: 92,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 802,
            main: 'Clouds',
            description: 'scattered clouds',
            icon: '03n',
        },
        cloudsInfo: {
            all: 28,
        },
        windInfo: {
            speed: 2.14,
            deg: 63,
            gust: 3.71,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0,
        partOfTheDay: 'n',
    },
    {
        time: '2023-08-25 00:00:00',
        mainInfo: {
            temp: 296.69,
            feels_like: 297.21,
            temp_min: 296.69,
            temp_max: 296.69,
            pressure: 1013,
            sea_level: 1013,
            grnd_level: 1011,
            humidity: 81,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 801,
            main: 'Clouds',
            description: 'few clouds',
            icon: '02d',
        },
        cloudsInfo: {
            all: 18,
        },
        windInfo: {
            speed: 1.45,
            deg: 85,
            gust: 3.16,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0,
        partOfTheDay: 'd',
    },
    {
        time: '2023-08-25 03:00:00',
        mainInfo: {
            temp: 302.12,
            feels_like: 304.29,
            temp_min: 302.12,
            temp_max: 302.12,
            pressure: 1013,
            sea_level: 1013,
            grnd_level: 1011,
            humidity: 61,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 801,
            main: 'Clouds',
            description: 'few clouds',
            icon: '02d',
        },
        cloudsInfo: {
            all: 20,
        },
        windInfo: {
            speed: 4.29,
            deg: 151,
            gust: 5.46,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0,
        partOfTheDay: 'd',
    },
    {
        time: '2023-08-25 06:00:00',
        mainInfo: {
            temp: 302.86,
            feels_like: 305.07,
            temp_min: 302.86,
            temp_max: 302.86,
            pressure: 1010,
            sea_level: 1010,
            grnd_level: 1008,
            humidity: 58,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 801,
            main: 'Clouds',
            description: 'few clouds',
            icon: '02d',
        },
        cloudsInfo: {
            all: 15,
        },
        windInfo: {
            speed: 6.68,
            deg: 157,
            gust: 7.25,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0,
        partOfTheDay: 'd',
    },
    {
        time: '2023-08-25 09:00:00',
        mainInfo: {
            temp: 300.48,
            feels_like: 302.48,
            temp_min: 300.48,
            temp_max: 300.48,
            pressure: 1010,
            sea_level: 1010,
            grnd_level: 1008,
            humidity: 69,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 801,
            main: 'Clouds',
            description: 'few clouds',
            icon: '02d',
        },
        cloudsInfo: {
            all: 13,
        },
        windInfo: {
            speed: 5.46,
            deg: 144,
            gust: 7.23,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0.06,
        partOfTheDay: 'd',
    },
    {
        time: '2023-08-25 12:00:00',
        mainInfo: {
            temp: 296.92,
            feels_like: 297.68,
            temp_min: 296.92,
            temp_max: 296.92,
            pressure: 1013,
            sea_level: 1013,
            grnd_level: 1011,
            humidity: 89,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 801,
            main: 'Clouds',
            description: 'few clouds',
            icon: '02n',
        },
        cloudsInfo: {
            all: 22,
        },
        windInfo: {
            speed: 3.36,
            deg: 129,
            gust: 6.1,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0.06,
        partOfTheDay: 'n',
    },
    {
        time: '2023-08-25 15:00:00',
        mainInfo: {
            temp: 296.5,
            feels_like: 297.27,
            temp_min: 296.5,
            temp_max: 296.5,
            pressure: 1014,
            sea_level: 1014,
            grnd_level: 1012,
            humidity: 91,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 500,
            main: 'Rain',
            description: 'light rain',
            icon: '10n',
        },
        cloudsInfo: {
            all: 40,
        },
        windInfo: {
            speed: 2.31,
            deg: 130,
            gust: 3.87,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0.2,
        partOfTheDay: 'n',
    },
    {
        time: '2023-08-25 18:00:00',
        mainInfo: {
            temp: 296.46,
            feels_like: 297.22,
            temp_min: 296.46,
            temp_max: 296.46,
            pressure: 1012,
            sea_level: 1012,
            grnd_level: 1010,
            humidity: 91,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 500,
            main: 'Rain',
            description: 'light rain',
            icon: '10n',
        },
        cloudsInfo: {
            all: 65,
        },
        windInfo: {
            speed: 2.3,
            deg: 137,
            gust: 4.68,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0.2,
        partOfTheDay: 'n',
    },
    {
        time: '2023-08-25 21:00:00',
        mainInfo: {
            temp: 295.66,
            feels_like: 296.39,
            temp_min: 295.66,
            temp_max: 295.66,
            pressure: 1012,
            sea_level: 1012,
            grnd_level: 1010,
            humidity: 93,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 804,
            main: 'Clouds',
            description: 'overcast clouds',
            icon: '04n',
        },
        cloudsInfo: {
            all: 98,
        },
        windInfo: {
            speed: 1.27,
            deg: 88,
            gust: 3.18,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0.12,
        partOfTheDay: 'n',
    },
    {
        time: '2023-08-26 00:00:00',
        mainInfo: {
            temp: 297.21,
            feels_like: 297.86,
            temp_min: 297.21,
            temp_max: 297.21,
            pressure: 1014,
            sea_level: 1014,
            grnd_level: 1012,
            humidity: 84,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 804,
            main: 'Clouds',
            description: 'overcast clouds',
            icon: '04d',
        },
        cloudsInfo: {
            all: 97,
        },
        windInfo: {
            speed: 1.86,
            deg: 89,
            gust: 3.27,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0.04,
        partOfTheDay: 'd',
    },
    {
        time: '2023-08-26 03:00:00',
        mainInfo: {
            temp: 301.82,
            feels_like: 304.07,
            temp_min: 301.82,
            temp_max: 301.82,
            pressure: 1013,
            sea_level: 1013,
            grnd_level: 1011,
            humidity: 63,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 804,
            main: 'Clouds',
            description: 'overcast clouds',
            icon: '04d',
        },
        cloudsInfo: {
            all: 99,
        },
        windInfo: {
            speed: 3.62,
            deg: 145,
            gust: 4.68,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0,
        partOfTheDay: 'd',
    },
    {
        time: '2023-08-26 06:00:00',
        mainInfo: {
            temp: 302.23,
            feels_like: 304.64,
            temp_min: 302.23,
            temp_max: 302.23,
            pressure: 1010,
            sea_level: 1010,
            grnd_level: 1008,
            humidity: 62,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 804,
            main: 'Clouds',
            description: 'overcast clouds',
            icon: '04d',
        },
        cloudsInfo: {
            all: 98,
        },
        windInfo: {
            speed: 5.97,
            deg: 157,
            gust: 6.52,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0.06,
        partOfTheDay: 'd',
    },
    {
        time: '2023-08-26 09:00:00',
        mainInfo: {
            temp: 300.17,
            feels_like: 301.87,
            temp_min: 300.17,
            temp_max: 300.17,
            pressure: 1010,
            sea_level: 1010,
            grnd_level: 1008,
            humidity: 68,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 804,
            main: 'Clouds',
            description: 'overcast clouds',
            icon: '04d',
        },
        cloudsInfo: {
            all: 94,
        },
        windInfo: {
            speed: 4.98,
            deg: 145,
            gust: 6.17,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0.11,
        partOfTheDay: 'd',
    },
    {
        time: '2023-08-26 12:00:00',
        mainInfo: {
            temp: 296.26,
            feels_like: 296.95,
            temp_min: 296.26,
            temp_max: 296.26,
            pressure: 1012,
            sea_level: 1012,
            grnd_level: 1010,
            humidity: 89,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 803,
            main: 'Clouds',
            description: 'broken clouds',
            icon: '04n',
        },
        cloudsInfo: {
            all: 73,
        },
        windInfo: {
            speed: 2.71,
            deg: 116,
            gust: 4.59,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0.06,
        partOfTheDay: 'n',
    },
    {
        time: '2023-08-26 15:00:00',
        mainInfo: {
            temp: 295.71,
            feels_like: 296.42,
            temp_min: 295.71,
            temp_max: 295.71,
            pressure: 1014,
            sea_level: 1014,
            grnd_level: 1012,
            humidity: 92,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 804,
            main: 'Clouds',
            description: 'overcast clouds',
            icon: '04n',
        },
        cloudsInfo: {
            all: 100,
        },
        windInfo: {
            speed: 1.55,
            deg: 108,
            gust: 2.39,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0,
        partOfTheDay: 'n',
    },
    {
        time: '2023-08-26 18:00:00',
        mainInfo: {
            temp: 295.86,
            feels_like: 296.54,
            temp_min: 295.86,
            temp_max: 295.86,
            pressure: 1012,
            sea_level: 1012,
            grnd_level: 1010,
            humidity: 90,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 500,
            main: 'Rain',
            description: 'light rain',
            icon: '10n',
        },
        cloudsInfo: {
            all: 94,
        },
        windInfo: {
            speed: 1.24,
            deg: 119,
            gust: 2.61,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0.2,
        partOfTheDay: 'n',
    },
    {
        time: '2023-08-26 21:00:00',
        mainInfo: {
            temp: 296.04,
            feels_like: 296.66,
            temp_min: 296.04,
            temp_max: 296.04,
            pressure: 1012,
            sea_level: 1012,
            grnd_level: 1010,
            humidity: 87,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 500,
            main: 'Rain',
            description: 'light rain',
            icon: '10n',
        },
        cloudsInfo: {
            all: 83,
        },
        windInfo: {
            speed: 1.48,
            deg: 72,
            gust: 3,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0.32,
        partOfTheDay: 'n',
    },
    {
        time: '2023-08-27 00:00:00',
        mainInfo: {
            temp: 297.09,
            feels_like: 297.63,
            temp_min: 297.09,
            temp_max: 297.09,
            pressure: 1014,
            sea_level: 1014,
            grnd_level: 1012,
            humidity: 80,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 804,
            main: 'Clouds',
            description: 'overcast clouds',
            icon: '04d',
        },
        cloudsInfo: {
            all: 91,
        },
        windInfo: {
            speed: 1.85,
            deg: 87,
            gust: 4.74,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0.08,
        partOfTheDay: 'd',
    },
    {
        time: '2023-08-27 03:00:00',
        mainInfo: {
            temp: 299.55,
            feels_like: 299.55,
            temp_min: 299.55,
            temp_max: 299.55,
            pressure: 1014,
            sea_level: 1014,
            grnd_level: 1012,
            humidity: 67,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 804,
            main: 'Clouds',
            description: 'overcast clouds',
            icon: '04d',
        },
        cloudsInfo: {
            all: 100,
        },
        windInfo: {
            speed: 3.04,
            deg: 144,
            gust: 4.69,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0,
        partOfTheDay: 'd',
    },
    {
        time: '2023-08-27 06:00:00',
        mainInfo: {
            temp: 301.21,
            feels_like: 302.47,
            temp_min: 301.21,
            temp_max: 301.21,
            pressure: 1011,
            sea_level: 1011,
            grnd_level: 1009,
            humidity: 58,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 804,
            main: 'Clouds',
            description: 'overcast clouds',
            icon: '04d',
        },
        cloudsInfo: {
            all: 94,
        },
        windInfo: {
            speed: 4.21,
            deg: 156,
            gust: 5.18,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0,
        partOfTheDay: 'd',
    },
    {
        time: '2023-08-27 09:00:00',
        mainInfo: {
            temp: 300.44,
            feels_like: 301.61,
            temp_min: 300.44,
            temp_max: 300.44,
            pressure: 1010,
            sea_level: 1010,
            grnd_level: 1008,
            humidity: 60,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 802,
            main: 'Clouds',
            description: 'scattered clouds',
            icon: '03d',
        },
        cloudsInfo: {
            all: 34,
        },
        windInfo: {
            speed: 4.81,
            deg: 151,
            gust: 5.6,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0.06,
        partOfTheDay: 'd',
    },
    {
        time: '2023-08-27 12:00:00',
        mainInfo: {
            temp: 295.92,
            feels_like: 296.5,
            temp_min: 295.92,
            temp_max: 295.92,
            pressure: 1012,
            sea_level: 1012,
            grnd_level: 1010,
            humidity: 86,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 801,
            main: 'Clouds',
            description: 'few clouds',
            icon: '02n',
        },
        cloudsInfo: {
            all: 19,
        },
        windInfo: {
            speed: 2.68,
            deg: 122,
            gust: 3.81,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0,
        partOfTheDay: 'n',
    },
    {
        time: '2023-08-27 15:00:00',
        mainInfo: {
            temp: 295.31,
            feels_like: 295.93,
            temp_min: 295.31,
            temp_max: 295.31,
            pressure: 1014,
            sea_level: 1014,
            grnd_level: 1011,
            humidity: 90,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 500,
            main: 'Rain',
            description: 'light rain',
            icon: '10n',
        },
        cloudsInfo: {
            all: 10,
        },
        windInfo: {
            speed: 1.98,
            deg: 89,
            gust: 3.13,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0.2,
        partOfTheDay: 'n',
    },
    {
        time: '2023-08-27 18:00:00',
        mainInfo: {
            temp: 294.92,
            feels_like: 295.53,
            temp_min: 294.92,
            temp_max: 294.92,
            pressure: 1012,
            sea_level: 1012,
            grnd_level: 1010,
            humidity: 91,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 500,
            main: 'Rain',
            description: 'light rain',
            icon: '10n',
        },
        cloudsInfo: {
            all: 31,
        },
        windInfo: {
            speed: 1.33,
            deg: 85,
            gust: 2.46,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0.28,
        partOfTheDay: 'n',
    },
    {
        time: '2023-08-27 21:00:00',
        mainInfo: {
            temp: 295.04,
            feels_like: 295.61,
            temp_min: 295.04,
            temp_max: 295.04,
            pressure: 1012,
            sea_level: 1012,
            grnd_level: 1010,
            humidity: 89,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 500,
            main: 'Rain',
            description: 'light rain',
            icon: '10n',
        },
        cloudsInfo: {
            all: 64,
        },
        windInfo: {
            speed: 1.31,
            deg: 53,
            gust: 2.32,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0.2,
        partOfTheDay: 'n',
    },
    {
        time: '2023-08-28 00:00:00',
        mainInfo: {
            temp: 296.78,
            feels_like: 297.29,
            temp_min: 296.78,
            temp_max: 296.78,
            pressure: 1014,
            sea_level: 1014,
            grnd_level: 1012,
            humidity: 80,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 803,
            main: 'Clouds',
            description: 'broken clouds',
            icon: '04d',
        },
        cloudsInfo: {
            all: 71,
        },
        windInfo: {
            speed: 1.21,
            deg: 52,
            gust: 1.75,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0.08,
        partOfTheDay: 'd',
    },
    {
        time: '2023-08-28 03:00:00',
        mainInfo: {
            temp: 301.14,
            feels_like: 302.59,
            temp_min: 301.14,
            temp_max: 301.14,
            pressure: 1013,
            sea_level: 1013,
            grnd_level: 1011,
            humidity: 60,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 803,
            main: 'Clouds',
            description: 'broken clouds',
            icon: '04d',
        },
        cloudsInfo: {
            all: 58,
        },
        windInfo: {
            speed: 3.79,
            deg: 152,
            gust: 4.47,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0,
        partOfTheDay: 'd',
    },
    {
        time: '2023-08-28 06:00:00',
        mainInfo: {
            temp: 300.08,
            feels_like: 301.43,
            temp_min: 300.08,
            temp_max: 300.08,
            pressure: 1011,
            sea_level: 1011,
            grnd_level: 1009,
            humidity: 64,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 803,
            main: 'Clouds',
            description: 'broken clouds',
            icon: '04d',
        },
        cloudsInfo: {
            all: 63,
        },
        windInfo: {
            speed: 4.87,
            deg: 155,
            gust: 5.23,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0,
        partOfTheDay: 'd',
    },
    {
        time: '2023-08-28 09:00:00',
        mainInfo: {
            temp: 299.83,
            feels_like: 301.02,
            temp_min: 299.83,
            temp_max: 299.83,
            pressure: 1010,
            sea_level: 1010,
            grnd_level: 1008,
            humidity: 63,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 802,
            main: 'Clouds',
            description: 'scattered clouds',
            icon: '03d',
        },
        cloudsInfo: {
            all: 33,
        },
        windInfo: {
            speed: 5.06,
            deg: 148,
            gust: 5.82,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0,
        partOfTheDay: 'd',
    },
    {
        time: '2023-08-28 12:00:00',
        mainInfo: {
            temp: 295.96,
            feels_like: 296.54,
            temp_min: 295.96,
            temp_max: 295.96,
            pressure: 1012,
            sea_level: 1012,
            grnd_level: 1010,
            humidity: 86,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 801,
            main: 'Clouds',
            description: 'few clouds',
            icon: '02n',
        },
        cloudsInfo: {
            all: 21,
        },
        windInfo: {
            speed: 2.9,
            deg: 117,
            gust: 4.73,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0,
        partOfTheDay: 'n',
    },
    {
        time: '2023-08-28 15:00:00',
        mainInfo: {
            temp: 295.02,
            feels_like: 295.64,
            temp_min: 295.02,
            temp_max: 295.02,
            pressure: 1013,
            sea_level: 1013,
            grnd_level: 1011,
            humidity: 91,
            temp_kf: 0,
        },
        weatherInfo: {
            id: 800,
            main: 'Clear',
            description: 'clear sky',
            icon: '01n',
        },
        cloudsInfo: {
            all: 1,
        },
        windInfo: {
            speed: 2.45,
            deg: 78,
            gust: 3.31,
        },
        visibilityInfo: 10000,
        precipitationInfo: 0,
        partOfTheDay: 'n',
    },
];
